export const projects2025 = [
    // 1. Water & Empowerment
    { id: 1, category: "Water & Empowerment", date: "Jan 2024 - Ongoing", titleEN: "Repair of All Damaged Boreholes", titleHA: "Gyaran Dukkan Rijiyoyin Burtsatse", desc: "Restored clean water access by repairing damaged boreholes across Gaya, Ajingi, and Albasu LGAs, benefiting thousands.", photos: ["/assets/images/gallery/1-Water-Empowerment/borehole-repair-all-lgas-jan2024-1.jpg", "/assets/images/gallery/1-Water-Empowerment/borehole-repairall-lgas-jan2024-1.jpg"] },
    { id: 2, category: "Water & Empowerment", date: "Dec 2024", titleEN: "20 Solar-Powered Boreholes Commissioned", titleHA: "Rijiyoyin Burtsatse na Solar 20", desc: "Sustainable solar boreholes for clean water in Asayaya Gafasa, Gaya Town, Kademi, Panda Tsohuwa, Daho, Kara Makama, and Jiyayya.", photos: ["/assets/images/gallery/1-Water-Empowerment/solar-borehole-gaya-town-gaya-dec2024-2.jpg", "/assets/images/gallery/1-Water-Empowerment/solar-borehole-asayaya-gafasa-gaya-dec2024-1.jpg"] },
    { id: 3, category: "Water & Empowerment", date: "Pre-2023", titleEN: "Renovation of Over 100 Boreholes", titleHA: "Gyaran Rijiyoyi Sama da 100", desc: "Major pre-election borehole renovations ensuring reliable water supply across the constituency.", photos: ["/assets/images/gallery/1-Water-Empowerment/borehole-repair-all-lgasjan2024-1.jpg"] },

    // 2. Electricity & Infrastructure
    { id: 4, category: "Electricity & Infrastructure", date: "Dec 2024", titleEN: "Transformer Installation (500KVA)", titleHA: "Samar da Tasfoma (500KVA)", desc: "New transformers installed in Kwalele, Panda, and Albasu wards to improve electricity supply in underserved areas.", photos: ["/assets/images/gallery/2-Electricity-Infrastructure/transformer-500kva-kwalele-panda-ward-albasu-dec2024-2.jpg", "/assets/images/gallery/2-Electricity-Infrastructure/transformer-kwalele-panda-albasu-dec2024-1.jpg"] },
    { id: 5, category: "Electricity & Infrastructure", date: "Pre-2023", titleEN: "Drainage and Culvert Reconstruction", titleHA: "Ginin Magudanan Ruwa", desc: "Rebuilt drainage and culverts in Fonda Gaya and other areas to prevent flooding and improve access roads.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-2.jpg"] }, // Placeholder updated to generic

    // 3. Lighting & Energy
    { id: 6, category: "Lighting & Energy", date: "Oct-Dec 2024", titleEN: "Solar Streetlights Installation (200+)", titleHA: "Fitilun Titi na Solar Sama da 200", desc: "Solar-powered streetlights installed in Gaya (Town, DSS, INEC), Albasu (78), and Ajingi (30) for enhanced security.", photos: ["/assets/images/gallery/3-Lighting-Energy/streetlight.jpg"] },
    { id: 7, category: "Lighting & Energy", date: "2024", titleEN: "Solar Batteries for Mosques", titleHA: "Batarin Solar na Masallatai", desc: "Provided solar batteries to Sharifawa and other mosques to support uninterrupted worship.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-1.jpg"] },

    // 4. Youth & Women Empowerment
    { id: 8, category: "Youth & Women", date: "Dec 2024", titleEN: "Motorcycle Empowerment Program", titleHA: "Tallafin Babura", desc: "Distributed motorcycles to youths in Gaya, Ajingi, and Albasu for mobility and income generation.", photos: ["/assets/images/gallery/4-Youth-Women-Empowerment/motorcycle-empowerment-21-units-dec2024-1.jpg", "/assets/images/gallery/4-Youth-Women-Empowerment/motorcycle-handover-5units-dec2024-1.jpg"] },
    { id: 9, category: "Youth & Women", date: "2024", titleEN: "Sewing & Grinding Machine Distribution", titleHA: "Kekunan Dinki da Injin Markade", desc: "400 Butterfly sewing machines to women, 70 grinding machines to youth, and 300 markade machines with flour.", photos: ["/assets/images/gallery/4-Youth-Women-Empowerment/butterfly-sewing-machines-400-women-2024-1.jpg", "/assets/images/gallery/4-Youth-Women-Empowerment/markade-machines-300-plus-flour-2024-1.jpg"] },
    { id: 10, category: "Youth & Women", date: "2024-2025", titleEN: "Cash Grants to Youth", titleHA: "Tallafin Kudi ga Matasa", desc: "Over ₦26 Million in cash grants to youth groups including Kwankwasiyya and D2D organizations.", photos: ["/assets/images/gallery/4-Youth-Women-Empowerment/cash-empowerment-20m-youths-march2024-1.jpg", "/assets/images/gallery/4-Youth-Women-Empowerment/d2d-grant-1-2m-june2025-1.jpg"] },

    // 5. Agriculture & Food Support
    { id: 11, category: "Agriculture & Food", date: "July 2024 - Aug 2025", titleEN: "Massive Fertilizer Distribution", titleHA: "Rabon Taki", desc: "Distribution of 1,800-2,000 bags of fertilizer to boost farming productivity across the constituency.", photos: ["/assets/images/gallery/5-Agriculture-Food-Support/fertilizer-distribution-1800-bags-aug2025-1.jpg", "/assets/images/gallery/5-Agriculture-Food-Support/fertilizer-distribution-bags-2024-1.jpg"] },
    { id: 12, category: "Agriculture & Food", date: "March 2024", titleEN: "Ramadan Relief (18,600 Bags)", titleHA: "Tallafin Azumi (Buhu 18,600)", desc: "Major distribution of 18,600 bags of grains and ₦320M in food/cash palliatives during Ramadan.", photos: ["/assets/images/gallery/4-Youth-Women-Empowerment/grains-distribution-18600-bags-ramadan-march2024-1.jpg", "/assets/images/gallery/5-Agriculture-Food-Support/palliatives-fasting-period-2024-1.jpg"] },
    { id: 13, category: "Agriculture & Food", date: "Nov 2024", titleEN: "Food Support to Mahauta Group", titleHA: "Tallafin Abinci ga Mahauta", desc: "50 bags of maize and millet distributed to the Mahauta group to reduce hunger.", photos: ["/assets/images/gallery/4-Youth-Women-Empowerment/food-support-mahauta-group-50-bags-nov2024-1.jpg"] },

    // 6. Education
    { id: 14, category: "Education", date: "2024-2025", titleEN: "School Blocks Construction", titleHA: "Ginin Azuzuwa", desc: "New primary school blocks in Hirullahi Bataiya, Zangon Gulya, Ganuwa Toranke, and Gaya GRA.", photos: ["/assets/images/gallery/6-Education/school-block-ganuwa-toranke-ajingi-2024-1.jpg", "/assets/images/gallery/6-Education/school-block-gaya-gra-2024-1.jpg"] },
    { id: 15, category: "Education", date: "2024-2025", titleEN: "Scholarships & Sponsorships", titleHA: "Tallafin Karatu", desc: "Sponsorships for 60 female nursing/midwifery students and financial support for KUST students.", photos: ["/assets/images/gallery/6-Education/nursing-scholarship-30-students-aug2025-1.jpg", "/assets/images/gallery/6-Education/female-scholarships-20-students-2024-1.jpg"] },

    // 7. Community & Health Support
    { id: 16, category: "Community & Health", date: "2024", titleEN: "Construction of Hospital in Faragai Ward", titleHA: "Ginin Asibiti a Mazabar Faragai", desc: "Construction of a new healthcare facility in Faragai Ward, Albasu LGA, to improve medical access for the community.", photos: ["/assets/images/gallery/7-Community-Health-Support/Hospital A mazabar Faragai, Karamar hukumar Albasu..jpg"] },
    { id: 17, category: "Community & Health", date: "Ongoing", titleEN: "Monthly Cash Allowances", titleHA: "Alawus na Wata-Wata", desc: "Consistent monthly stipends provided to over 100 vulnerable families.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-2.jpg"] },

    // 8. Legislative & Political
    { id: 18, category: "Legislative", date: "2023-2025", titleEN: "Sponsored Bills & Motions", titleHA: "Kudirori a Majalisa", desc: "Legislative activism including bills on health/agric colleges and over 50 motions for development.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-1.jpg"] },
    { id: 19, category: "Legislative", date: "Late 2024", titleEN: "Opposition to Tax Reform Bills", titleHA: "Kin Amincewa da Kudirin Haraji", desc: "Publicly opposed the Tax Reform Bills, advocating for the masses against ill-timed taxation.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-3.jpg"] },

    // 9. Pre-Assumption & Other Initiatives
    { id: 20, category: "Community Construction", date: "Pre-2023", titleEN: "Mosque Constructions", titleHA: "Ginin Masallatai", desc: "Renovation and construction of mosques in Gazama Wurumanga, Mangari Fulani, and other wards.", photos: ["/assets/images/gallery/0-Portraits-Official/kano%20governor.jpg"] },
    { id: 21, category: "Infrastructure", date: "Pre-2023", titleEN: "Overhead Tanks & Culverts", titleHA: "Ginin Tankunan Ruwa", desc: "Construction of overhead tanks and culverts in Zangon Gulya and Fonda Gaya.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-.jpg"] },
    { id: 22, category: "Community Support", date: "Pre-2023", titleEN: "Donations to Schools & Mosques", titleHA: "Tallafi ga Makarantu da Masallatai", desc: "Donated land, chairs, mats, and water pumps, plus school fees for orphans.", photos: ["/assets/images/gallery/0-Portraits-Official/portrait-2.jpg"] },
    { id: 23, category: "Education", date: "Pre-2023", titleEN: "University Sponsorships", titleHA: "Daukar Nauyin Dalibai", desc: "Sponsorships for students at Bayero University and Al-Istiqama University.", photos: ["/assets/images/gallery/6-Education/ursing-midwifery-sponsorship-60-female-2024-1.jpg"] }, // Placeholder
    { id: 24, category: "Empowerment", date: "2023-2025", titleEN: "Overall Empowerment & Palliatives", titleHA: "Jimillar Tallafi", desc: "Over ₦320 Million deployed in food and cash support, benefiting over 19,000 people across the constituency.", photos: ["/assets/images/gallery/5-Agriculture-Food-Support/palliatives-fasting-period-2024-1.jpg"] }
];
